name = "MonteCarloTesting"
uuid = "b75b2f39-c526-438a-aeb3-f18deacfdc57"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25"
EllipsisNotation = "1.1"
SplitApplyCombine = "1.1"
julia = "1.6"
